### PR TITLE
Fix Editor UI

### LINKED ISSUE #80: Wrong Editor UI
**Describe the Bug**
There are some UI glitches in the Editor view.
1. There is no padding under the body
2. Missing box around the Response Headers and Response Body

**To Reproduce**
1. Go to Editor section
2. Select and API or create a new one

**Expected behavior**
There is a padding under the body and the Response Headers and Response Body are inside a gray box.

**Screenshots**
| Mocka | Figma |
|-------|--------|
| Screenshot 2021-04-22 at 17 00 18 |  |

**Configuration**
OS and Version: macOS 11.2

**Additional Context**
None.

### PR DESCRIPTION
**Pull request by MicheleMola**
# Description

This PR fixes the Editor UI.

Fixes #80 

## Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshots 

Schermata 2021-04-22 alle 18 27 59

Schermata 2021-04-22 alle 18 30 07

### CODE REVIEW

**Review by FabrizioBrancati — COMMENTED** [review]
We should also remove the `isVisible` function because is not flexible like `isHidden`, otherwise we should let it be flexible as `isHidden`...

**Comment by TheInkedEngineer** [comment]
@FabrizioBrancati what do you mean by "is not flexible"?

**Review by TheInkedEngineer — APPROVED** [review]

**Comment by FabrizioBrancati** [comment]
> @FabrizioBrancati what do you mean by "is not flexible"?

The signature of `isHidden(_ hidden: Bool, remove: Bool = false)` allows the complete removal of the `View`, meanwhile the signature of `isVisible(_ visible: Bool)` doesn't allow that. We should add the `remove` parameter` too

**Comment by MicheleMola** [comment]
@FabrizioBrancati Yes, this is the reason I added `if` and removed `isVisible`.

**Review by martin-e91 — APPROVED** [review]

**Review by FabrizioBrancati — APPROVED** [review]
LGTM 👍

**Pull request merged**
